CREATE TABLE t_client (
    id            BIGSERIAL PRIMARY KEY,
    created  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE t_order (
    id            BIGSERIAL PRIMARY KEY,
    created  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    start_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    client_id BIGINT,
    state TEXT NOT NULL,
    CONSTRAINT t_order_client_id_fk FOREIGN KEY (client_id) REFERENCES t_client(id)
);