version: "3"

services:
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: pool-postgres
    env_file:
      .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB={DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  db: