spring:
  liquibase:
    enabled: true
    change-log: db/master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

