spring:
  liquibase:
    enabled: true
    change-log: db/master.yml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}
    username: ${DB_USER:root}
    password: ${DB_USER:root}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

limits:
  max-orders-per-time: 10